# Generated by Django 5.2.6 on 2025-09-09 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connecta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, help_text='Se está ativo como Conecta')),
                ('mandate_start', models.DateField(blank=True, null=True)),
                ('mandate_end', models.DateField(blank=True, null=True)),
                ('capacity_max', models.PositiveIntegerField(default=12, help_text='Número máximo de pessoas que pode atender')),
                ('assigned_count', models.PositiveIntegerField(default=0, help_text='Número atual de pessoas atribuídas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conecta',
                'verbose_name_plural': 'Conectas',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ConnectaHomologation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homologated_at', models.DateTimeField(auto_now_add=True)),
                ('total_preferences', models.PositiveIntegerField(help_text='Total de preferências processadas')),
                ('approved_connectas', models.PositiveIntegerField(help_text='Conectas aprovados (≥2 votos)')),
                ('rejected_preferences', models.PositiveIntegerField(help_text='Preferências rejeitadas (<2 votos)')),
                ('notes', models.TextField(blank=True, help_text='Observações sobre a homologação')),
            ],
            options={
                'verbose_name': 'Homologação de Conecta',
                'verbose_name_plural': 'Homologações de Conectas',
                'ordering': ['-homologated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectaPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_change_at', models.DateTimeField(help_text='Próxima data permitida para mudança')),
                ('effective', models.BooleanField(default=False, help_text='Se a escolha foi homologada (≥2 votos)')),
                ('vote_count', models.PositiveIntegerField(default=0, help_text='Número de votos que o conecta escolhido tem')),
            ],
            options={
                'verbose_name': 'Preferência de Conecta',
                'verbose_name_plural': 'Preferências de Conecta',
                'ordering': ['-chosen_at'],
            },
        ),
    ]
