# Generated by Django 5.2.6 on 2025-09-09 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connectas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='connecta',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connecta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connectahomologation',
            name='homologated_by',
            field=models.ForeignKey(help_text='Admin que fez a homologação', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connectapreference',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connecta_pref', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connectapreference',
            name='preferred_connecta',
            field=models.ForeignKey(help_text='Conecta escolhido pelo colaborador', on_delete=django.db.models.deletion.PROTECT, related_name='preferred_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
