# Generated by Django 5.2.6 on 2025-09-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_connecta',
            field=models.BooleanField(default=False, help_text='Colaboradores podem ser designados como Conectas', verbose_name='É um Conecta'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('colaborador', 'Colaborador'), ('diretoria', 'Diretoria'), ('admin', 'Admin')], default='colaborador', max_length=20, verbose_name='Papel'),
        ),
    ]
