# Generated by Django 5.2.6 on 2025-09-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_connecta_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto opcional do usuário', null=True, upload_to='user_photos/', verbose_name='Foto de Perfil'),
        ),
    ]
