# Generated by Django 5.2.6 on 2025-09-10 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Conecta ou supervisor responsável por este usuário', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_users', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor/Conecta Superior'),
        ),
    ]
