# Generated by Django 5.2.6 on 2025-09-09 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectaAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Atribuição')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('connecta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_employees', to=settings.AUTH_USER_MODEL, verbose_name='Conecta')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connecta_assignment', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Atribuição de Conecta',
                'verbose_name_plural': 'Atribuições de Conectas',
            },
        ),
        migrations.CreateModel(
            name='ConnectaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text='Descrição sobre experiência e especialidades', verbose_name='Biografia')),
                ('specialties', models.JSONField(default=list, help_text="Lista de especialidades como ['Bem-estar', 'Liderança', 'Tech Career']", verbose_name='Especialidades')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível para novos colaboradores')),
                ('max_assignments', models.PositiveIntegerField(default=10, verbose_name='Máximo de colaboradores')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connecta_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Conecta',
                'verbose_name_plural': 'Perfis de Conectas',
            },
        ),
    ]
