# Generated by Django 5.2.6 on 2025-09-09 19:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalatedCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Caso')),
                ('description', models.TextField(verbose_name='Descrição Detalhada')),
                ('category', models.CharField(choices=[('harassment', 'Assédio'), ('discrimination', 'Discriminação'), ('workplace_conflict', 'Conflito no Trabalho'), ('mental_health', 'Saúde Mental'), ('working_conditions', 'Condições de Trabalho'), ('leadership_issues', 'Problemas de Liderança'), ('team_dynamics', 'Dinâmica de Equipe'), ('career_development', 'Desenvolvimento de Carreira'), ('compensation', 'Remuneração'), ('policy_violation', 'Violação de Política'), ('other', 'Outros')], max_length=50, verbose_name='Categoria')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Andamento'), ('resolved', 'Resolvido'), ('closed', 'Fechado')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escalated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Caso Anônimo')),
                ('requires_immediate_attention', models.BooleanField(default=False, verbose_name='Requer Atenção Imediata')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de Resolução')),
                ('follow_up_required', models.BooleanField(default=False, verbose_name='Requer Acompanhamento')),
                ('follow_up_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Acompanhamento')),
                ('assigned_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_cases_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Diretor Responsável')),
                ('connecta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_cases_created', to=settings.AUTH_USER_MODEL, verbose_name='Conecta que Escalou')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_about_me', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador Envolvido')),
            ],
            options={
                'verbose_name': 'Caso Escalado',
                'verbose_name_plural': 'Casos Escalados',
                'ordering': ['-escalated_at', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Conteúdo da Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_internal', models.BooleanField(default=False, verbose_name='Nota Interna')),
                ('is_visible_to_connecta', models.BooleanField(default=True, verbose_name='Visível para Conecta')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='escalation.escalatedcase')),
            ],
            options={
                'verbose_name': 'Nota do Caso',
                'verbose_name_plural': 'Notas dos Casos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('escalated', 'Caso Escalado'), ('assigned', 'Caso Atribuído'), ('status_changed', 'Status Alterado'), ('priority_changed', 'Prioridade Alterada'), ('note_added', 'Nota Adicionada'), ('meeting_scheduled', 'Reunião Agendada'), ('investigation_started', 'Investigação Iniciada'), ('resolution_proposed', 'Resolução Proposta'), ('case_resolved', 'Caso Resolvido'), ('case_closed', 'Caso Fechado'), ('follow_up_scheduled', 'Acompanhamento Agendado')], max_length=50)),
                ('description', models.TextField(verbose_name='Descrição da Ação')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('old_value', models.CharField(blank=True, max_length=200)),
                ('new_value', models.CharField(blank=True, max_length=200)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='escalation.escalatedcase')),
            ],
            options={
                'verbose_name': 'Ação do Caso',
                'verbose_name_plural': 'Ações dos Casos',
                'ordering': ['-performed_at'],
            },
        ),
    ]
