# Generated by Django 4.2.24 on 2025-09-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casenote',
            name='case',
        ),
        migrations.RemoveField(
            model_name='casenote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='escalatedcase',
            name='assigned_director',
        ),
        migrations.RemoveField(
            model_name='escalatedcase',
            name='connecta',
        ),
        migrations.RemoveField(
            model_name='escalatedcase',
            name='employee',
        ),
        migrations.DeleteModel(
            name='CaseAction',
        ),
        migrations.DeleteModel(
            name='CaseNote',
        ),
        migrations.DeleteModel(
            name='EscalatedCase',
        ),
    ]
