# Generated by Django 5.2.6 on 2025-09-09 13:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connectas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoicePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pseudo_id', models.CharField(db_index=True, help_text='Pseudônimo anonimizado do autor', max_length=64)),
                ('visibility', models.CharField(choices=[('connecta_ident', 'Conecta (identificado)'), ('connecta_anon', 'Conecta (anônimo)')], default='connecta_ident', help_text='Nível de privacidade perante o Conecta', max_length=20)),
                ('sentiment', models.CharField(choices=[('positivo', 'Positivo'), ('alerta', 'Alerta'), ('denuncia', 'Denúncia')], help_text='Classificação do relato', max_length=10)),
                ('text', models.TextField(help_text='Conteúdo do relato')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags para categorização')),
                ('gostaria_retorno', models.BooleanField(default=False, help_text='Se o autor quer conversar sobre o relato')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_analise', 'Em Análise'), ('resolvido', 'Resolvido'), ('escalado', 'Escalado')], default='novo', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_posts', to='connectas.connecta')),
                ('author', models.ForeignKey(blank=True, help_text='Pode ser nulo para reforço de anonimato', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relato de Voz',
                'verbose_name_plural': 'Relatos de Voz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Arquivo anexado ao relato', upload_to='voice_attachments/%Y/%m/')),
                ('filename', models.CharField(help_text='Nome original do arquivo', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='voice.voicepost')),
            ],
            options={
                'verbose_name': 'Anexo de Relato',
                'verbose_name_plural': 'Anexos de Relatos',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField(default=list, help_text="Array de mensagens: [{from:'autor|connecta', at:'ISO', text:'...'}]")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='voice.voicepost')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
            },
        ),
        migrations.AddIndex(
            model_name='voicepost',
            index=models.Index(fields=['status', 'created_at'], name='voice_voice_status_d434f1_idx'),
        ),
        migrations.AddIndex(
            model_name='voicepost',
            index=models.Index(fields=['sentiment'], name='voice_voice_sentime_5c1036_idx'),
        ),
    ]
