# Generated by Django 5.2.6 on 2025-09-09 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PseudonymSalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex: 2025-01', max_length=20, unique=True)),
                ('salt', models.CharField(help_text='Salt criptográfico para pseudônimos', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salt de Pseudônimo',
                'verbose_name_plural': 'Salts de Pseudônimos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('day', models.DateField(db_index=True)),
                ('score', models.PositiveSmallIntegerField(help_text='Humor de 1 a 5')),
                ('comment', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags opcionais para categorização')),
                ('pseudo_id', models.CharField(db_index=True, help_text='Pseudônimo anonimizado do usuário', max_length=64)),
            ],
            options={
                'verbose_name': 'Check-in de Humor',
                'verbose_name_plural': 'Check-ins de Humor',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('day', 'pseudo_id'), name='unique_daily_checkin')],
            },
        ),
    ]
