# Generated by Django 5.2.6 on 2025-09-09 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuralComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(help_text='Conteúdo do comentário')),
                ('anonymous', models.BooleanField(default=False, help_text='Se o comentário é anônimo')),
                ('status', models.CharField(choices=[('publicado', 'Publicado'), ('ocultado', 'Ocultado')], default='publicado', max_length=12)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Comentário do Mural',
                'verbose_name_plural': 'Comentários do Mural',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MuralPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('team', models.CharField(db_index=True, help_text='Equipe/departamento do post', max_length=120)),
                ('text', models.TextField(help_text='Conteúdo do post')),
                ('emoji', models.PositiveSmallIntegerField(blank=True, help_text='Emoji de humor (1-5), opcional', null=True)),
                ('anonymous', models.BooleanField(default=False, help_text='Se o post é anônimo para a equipe')),
                ('status', models.CharField(choices=[('publicado', 'Publicado'), ('ocultado', 'Ocultado')], default='publicado', max_length=12)),
                ('reactions', models.JSONField(blank=True, default=dict, help_text="Reações por emoji: {'👍': 3, '🎉': 5}")),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_reason', models.TextField(blank=True, help_text='Motivo da moderação')),
            ],
            options={
                'verbose_name': 'Post do Mural',
                'verbose_name_plural': 'Posts do Mural',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MuralReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(help_text='Emoji da reação', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reação do Mural',
                'verbose_name_plural': 'Reações do Mural',
            },
        ),
    ]
