# Generated by Django 5.2.6 on 2025-09-09 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mural', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='muralcomment',
            name='author',
            field=models.ForeignKey(help_text='Autor do comentário', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='muralcomment',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='muralpost',
            name='created_by',
            field=models.ForeignKey(help_text='Autor do post (sempre armazenado para moderação)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='muralpost',
            name='moderated_by',
            field=models.ForeignKey(blank=True, help_text='Quem moderou o post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='muralcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mural.muralpost'),
        ),
        migrations.AddField(
            model_name='muralreaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reactions', to='mural.muralpost'),
        ),
        migrations.AddField(
            model_name='muralreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='muralpost',
            index=models.Index(fields=['team', 'status', 'created_at'], name='mural_mural_team_b85e80_idx'),
        ),
        migrations.AddIndex(
            model_name='muralpost',
            index=models.Index(fields=['created_at'], name='mural_mural_created_8d4cb1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='muralreaction',
            unique_together={('post', 'user', 'emoji')},
        ),
    ]
