# Generated by Django 5.2.6 on 2025-09-09 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas e observações do caso')),
                ('actions', models.JSONField(default=list, help_text='Histórico de ações: [{at, by, action, details}]')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em Andamento'), ('fechado', 'Fechado')], default='aberto', max_length=20)),
                ('resolution_summary', models.TextField(blank=True, help_text='Resumo da resolução final')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Caso do Conselho',
                'verbose_name_plural': 'Casos do Conselho',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouncilDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(choices=[('intervencao', 'Intervenção'), ('investigacao', 'Investigação'), ('capacitacao', 'Capacitação'), ('mudanca_processo', 'Mudança de Processo'), ('arquivamento', 'Arquivamento'), ('outros', 'Outros')], max_length=20)),
                ('description', models.TextField(help_text='Descrição da decisão tomada')),
                ('deadline', models.DateField(blank=True, help_text='Prazo para execução', null=True)),
                ('executed', models.BooleanField(default=False, help_text='Se a decisão foi executada')),
                ('execution_notes', models.TextField(blank=True, help_text='Notas sobre a execução')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Decisão do Conselho',
                'verbose_name_plural': 'Decisões do Conselho',
                'ordering': ['-created_at'],
            },
        ),
    ]
