# Generated by Django 5.2.6 on 2025-09-09 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('council', '0001_initial'),
        ('voice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='councilcase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Membro do conselho responsável', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='councilcase',
            name='escalated_by',
            field=models.ForeignKey(help_text='Conecta que escalou o caso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='councilcase',
            name='source_post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='council_case', to='voice.voicepost'),
        ),
        migrations.AddField(
            model_name='councildecision',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='council.councilcase'),
        ),
        migrations.AddField(
            model_name='councildecision',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='Responsável pela execução', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='councilcase',
            index=models.Index(fields=['status', 'priority'], name='council_cou_status_b2451f_idx'),
        ),
        migrations.AddIndex(
            model_name='councilcase',
            index=models.Index(fields=['created_at'], name='council_cou_created_3c1666_idx'),
        ),
    ]
