# Generated by Django 5.2.6 on 2025-09-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('mood_index', 'Índice de Humor'), ('voice_summary', 'Resumo de Relatos'), ('resolution_time', 'Tempo de Resolução'), ('top_themes', 'Temas Principais'), ('team_comparison', 'Comparação de Equipes'), ('trend_chart', 'Gráfico de Tendência')], max_length=20)),
                ('title', models.CharField(help_text='Título do widget', max_length=100)),
                ('position', models.PositiveIntegerField(default=0, help_text='Posição no dashboard')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configurações específicas do widget')),
                ('active', models.BooleanField(default=True, help_text='Se o widget está ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Widget do Dashboard',
                'verbose_name_plural': 'Widgets do Dashboard',
                'ordering': ['user', 'position'],
            },
        ),
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('export_type', models.CharField(choices=[('clima_csv', 'Relatório de Clima (CSV)'), ('voice_aggregated', 'Relatos Agregados'), ('mood_aggregated', 'Humor Agregado'), ('audit_logs', 'Logs de Auditoria'), ('bulletin_pdf', 'Boletim (PDF)')], max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Filtros aplicados na exportação')),
                ('records_count', models.PositiveIntegerField(help_text='Número de registros exportados')),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, help_text='Tamanho do arquivo gerado', null=True)),
                ('download_expires_at', models.DateTimeField(blank=True, help_text='Quando o link de download expira', null=True)),
            ],
            options={
                'verbose_name': 'Log de Exportação',
                'verbose_name_plural': 'Logs de Exportações',
                'ordering': ['-exported_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do boletim', max_length=200)),
                ('team', models.CharField(db_index=True, help_text='Equipe/departamento do boletim', max_length=120)),
                ('foi_bem', models.TextField(help_text='O que foi bem na semana')),
                ('preocupa', models.TextField(help_text='O que preocupa/precisa atenção')),
                ('proximos_passos', models.TextField(help_text='Próximos passos e ações')),
                ('week_start', models.DateField(help_text='Início da semana referente')),
                ('week_end', models.DateField(help_text='Fim da semana referente')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('mood_summary', models.JSONField(blank=True, default=dict, help_text='Resumo das métricas de humor da semana')),
                ('voice_summary', models.JSONField(blank=True, default=dict, help_text='Resumo dos relatos da semana')),
            ],
            options={
                'verbose_name': 'Boletim da Equipe',
                'verbose_name_plural': 'Boletins das Equipes',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='ClimaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('period_type', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral')], default='daily', max_length=10)),
                ('department', models.CharField(blank=True, help_text='Departamento específico ou geral', max_length=120, null=True)),
                ('team', models.CharField(blank=True, help_text='Equipe específica ou geral', max_length=120, null=True)),
                ('mood_index', models.FloatField(blank=True, help_text='Índice de humor 0-100 (null se n<5)', null=True)),
                ('mood_count', models.PositiveIntegerField(default=0, help_text='Número de check-ins considerados')),
                ('mood_collecting', models.BooleanField(default=True, help_text='Se ainda está coletando dados (n<5)')),
                ('voice_total', models.PositiveIntegerField(default=0, help_text='Total de relatos no período')),
                ('voice_positivo', models.PositiveIntegerField(default=0)),
                ('voice_alerta', models.PositiveIntegerField(default=0)),
                ('voice_denuncia', models.PositiveIntegerField(default=0)),
                ('voice_resolvido', models.PositiveIntegerField(default=0)),
                ('voice_escalado', models.PositiveIntegerField(default=0)),
                ('avg_resolution_time', models.FloatField(blank=True, help_text='Tempo médio de resolução em horas', null=True)),
                ('top_themes', models.JSONField(blank=True, default=list, help_text='Lista de temas mais citados com contagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Snapshot de Clima',
                'verbose_name_plural': 'Snapshots de Clima',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'period_type'], name='reports_cli_date_d77918_idx'), models.Index(fields=['department', 'team'], name='reports_cli_departm_10aebf_idx')],
                'unique_together': {('date', 'period_type', 'department', 'team')},
            },
        ),
    ]
