# Generated by Django 5.2.6 on 2025-09-09 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwidget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportlog',
            name='exported_by',
            field=models.ForeignKey(help_text='Usuário que fez a exportação', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teambulletin',
            name='created_by',
            field=models.ForeignKey(help_text='Conecta que criou o boletim', on_delete=django.db.models.deletion.CASCADE, related_name='created_bulletins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardwidget',
            unique_together={('user', 'widget_type')},
        ),
        migrations.AddIndex(
            model_name='teambulletin',
            index=models.Index(fields=['team', 'status'], name='reports_tea_team_0fef53_idx'),
        ),
        migrations.AddIndex(
            model_name='teambulletin',
            index=models.Index(fields=['week_start'], name='reports_tea_week_st_c880d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teambulletin',
            unique_together={('team', 'week_start')},
        ),
    ]
